### ISSUE TITLE
Suggest paper to add

### ISSUE THREAD

**Issue by MichalZnalezniak** [yueliu1999/Awesome-Deep-Graph-Clustering#29]
Hello, thanks for keeping the repository up to date with new papers.
I would like to suggest adding our paper "Contrastive Hierarchical Clustering" to the "Deep Clustering" category or it could also be added to the new category "Deep Hierarchical Clustering".

Link to paper: https://arxiv.org/abs/2303.03389
Link to code: https://github.com/MichalZnalezniak/Contrastive-Hierarchical-Clustering
Venue: ECML PKDD

Thanks!

**Comment by buffaloiron** [comment]
您好,你的邮件我已经收到,祝学业有成!工作顺利! --王晓栋I have recieved your e-mail,and I will reply you as soon as possible. Hope you have every successful on education and work! --xiaodong wang

**Comment by yueliu1999** [comment]
Hi, thanks for your wonderful work! You can create a new pull request to add your paper and code.

**Comment by MichalZnalezniak** [comment]
Sure! I've created the PR #30.  Let me know if you are okay with it.

**Comment by yueliu1999** [comment]
I have merged it. Thanks for your contribution!
